### ISSUE TITLE
Bluelight is dead. Others need to be added to this list.

### ISSUE THREAD

**Issue by AvgZing** [xinghao2003/MCBE-ServerSoftware-List#16]
Bluelight is OFFICIALLY discontinued. I will also make a PR including more php softwares. First, please let me know: what makes a software count as "discontinued"? Smt like inactive for more than a month?

**Comment by AvgZing** [comment]
Hold on, never mind. Bluelight is active again. Hadnt checked for a while... But still please answer the question

**Comment by xinghao2003** [comment]
Yes，not active more than a month count as discontinued

**Comment by AvgZing** [comment]
Okay, thanks! I'll add a few

**Comment by Nekiechan** [comment]
if only all the fork dev's united and created one huge project

**Comment by AvgZing** [comment]
Ah that would be beautiful

**Comment by Vaults1** [comment]
If you look at the discontinued list, it's massive. Spoon devs should contribute to the official PMMP, because all of them fail eventually.

**Comment by haniokasai** [comment]
Bluelight is in developing.

**Comment by Nekiechan** [comment]
Im developing a project all on my own, and it's sure painful

**Comment by Nekiechan** [comment]
Ultie0, most people dont contribute to PMMP because they have their own ideas that PMMP wont approve of.

**Comment by AvgZing** [comment]
Exactly, @Nekiechan

**Comment by Nekiechan** [comment]
@TheRoyalBlock btw what you working on? may i ask?

**Comment by AvgZing** [comment]
I mostly chat and give support, I am not working on any softwares of my own. I love building vast expanses of worlds and atm I am waiting for my server's machine to be done.

**Comment by Nekiechan** [comment]
@TheRoyalBlock well gl on your work ^~^

**Comment by AvgZing** [comment]
Thanks! I wish you ease of coding in return.
