### ISSUE TITLE
Can you add spigotpe

### ISSUE THREAD

**Issue by ghost** [xinghao2003/MCBE-ServerSoftware-List#2]
https://github.com/spigotpe-beta/Spigotpe

**Comment by xinghao2003** [comment]
Added - https://github.com/xinghao2003/MCPE-ServerSoftware-List/commit/2660bb8d1856060dedf88585ed753f6f00dad2a3

**Comment by ghost** [comment]
That is fake and a copy

**Comment by xinghao2003** [comment]
Why?

**Comment by ghost** [comment]
This person cannot code. Also the name spigot is copyrighted and they cannot just add PE to the end. Same with IMReactive

**Comment by xinghao2003** [comment]
Oh Okay
