### ISSUE TITLE
2 new server softwares

### ISSUE THREAD

**Issue by MrDiamond64** [xinghao2003/MCBE-ServerSoftware-List#56]
Opentouch: https://github.com/ApexieDevelopment/OpenTouch

Kookie: https://github.com/organization/Kookie

**Comment by MonoAdrian23** [comment]
What are you talking?
It isnt discontinued

**Comment by MrDiamond64** [comment]
> What are you talking?
> It isnt discontinued

Oops I just saw that the last release was 1 month ago so I thought it was discontinued.

**Comment by MonoAdrian23** [comment]
At next, you cant think a Software is discontinued because there is no Update since months.
Is Powernukkit added?
No!
Powernukkit have stable releases.
You can mark Altay as outdated.
No Releases since Years.
