### ISSUE TITLE
License, and reproduction rights?

### ISSUE THREAD

**Issue by SirLich** [xinghao2003/MCBE-ServerSoftware-List#58]
Hello! I am the owner of the [Bedrock OSS Organization](https://github.com/Bedrock-OSS), the maintenance team behind [Bedrock Wiki](https://wiki.bedrock.dev/). 

We have had an [open issue about BDS software](https://github.com/Bedrock-OSS/bedrock-wiki/issues/145) for quite some time. 

As this repository is unlicensed, its unclear whether you would feel comfortable having it migrated. Additionally, a migration is a bit silly if this repo stays the "source of truth", meaning the wiki page would become out-dated. 

Do you have any particular thoughts on the matter?

If you feel its important that the list stays here, a potential undesirable solution would be to have this repo added to our [useful links page.](https://wiki.bedrock.dev/meta/useful-links.html).

**Comment by SirLich** [comment]
This list would sit alongside other howto pages in the BDS-space.

**Comment by xinghao2003** [comment]
Since I didn't maintain this repo for a long time, so it's better for someone else can continue updating it. Hence, I am totally fine with the migration. When the migration is completed, I will add a link that points to your page.

**Comment by SirLich** [comment]
Page here: https://wiki.bedrock.dev/servers/server-software.html

I've also sent in a PR -you can decide whether its acceptable or not.
